#!/usr/bin/env bash

#Displaying Best School 10 times till the 4-if_9 iteration using   loop
i=1



while [ "$i" -lt 11 ]; do

    echo "Best School"

    if [[ $i -eq 9 ]]; then

        echo "Hi"

    fi    

    ((i++))

done
